# Generated by Django 4.0.3 on 2022-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_data_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
